// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzf9jgpYrERwwKsWxOxTp4KiqEDP2opJY',
    appId: '1:24855817122:web:fe1baa6d8656f9906b20fb',
    messagingSenderId: '24855817122',
    projectId: 'ninja-brew-flutter-firebase',
    authDomain: 'ninja-brew-flutter-firebase.firebaseapp.com',
    storageBucket: 'ninja-brew-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCbb2ywduHwc4ClLRPUxMcy1YNBWjvXY',
    appId: '1:24855817122:android:46c1e77a8ea1f9636b20fb',
    messagingSenderId: '24855817122',
    projectId: 'ninja-brew-flutter-firebase',
    storageBucket: 'ninja-brew-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGUsbshuMdCPn_KSlKUHICBjEgb8N8w4Q',
    appId: '1:24855817122:ios:e3e2200755237c436b20fb',
    messagingSenderId: '24855817122',
    projectId: 'ninja-brew-flutter-firebase',
    storageBucket: 'ninja-brew-flutter-firebase.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNetninja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGUsbshuMdCPn_KSlKUHICBjEgb8N8w4Q',
    appId: '1:24855817122:ios:97d43b9ac95498956b20fb',
    messagingSenderId: '24855817122',
    projectId: 'ninja-brew-flutter-firebase',
    storageBucket: 'ninja-brew-flutter-firebase.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNetninja.RunnerTests',
  );
}
